<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:sch="http://example.com/"
                  xmlns:tns="http://example.com/" targetNamespace="http://example.com/">
  
    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://example.com/" schemaLocation="person.xsd" />
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="personRequest">
        <wsdl:part element="tns:personRequest" name="personRequest">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="personResponse">
        <wsdl:part element="tns:personResponse" name="personResponse">
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="ServiceException">
        <wsdl:part element="tns:ServiceException" name="ServiceException">
        </wsdl:part>
    </wsdl:message>
    <wsdl:portType name="PersonPort">
        <wsdl:operation name="getPerson">
            <wsdl:input message="tns:personRequest" name="personRequest">
            </wsdl:input>
            <wsdl:output message="tns:personResponse" name="personResponse">
            </wsdl:output>
            <wsdl:fault message="tns:ServiceException" name="ServiceException">
            </wsdl:fault>            
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="PersonPortSoap11" type="tns:PersonPort">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getPerson">
            <soap:operation soapAction=""/>
            <wsdl:input name="personRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="personResponse">
                <soap:body use="literal"/>
            </wsdl:output>
            <wsdl:fault name="ServiceException">
                <soap:fault name="ServiceException" use="literal"/>
            </wsdl:fault>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="PersonPortService">
        <wsdl:port binding="tns:PersonPortSoap11" name="PersonPortSoap11">
            <soap:address location="http://localhost:1879/soap/person"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>