//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.06 at 04:11:36 PM MSK 
//


package com.example;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PersonRequest_QNAME = new QName("http://example.com/", "personRequest");
    private final static QName _OriginRequest_QNAME = new QName("http://example.com/", "originRequest");
    private final static QName _PersonResponse_QNAME = new QName("http://example.com/", "personResponse");
    private final static QName _ServiceException_QNAME = new QName("http://example.com/", "ServiceException");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PersonResponse }
     * 
     */
    public PersonResponse createPersonResponse() {
        return new PersonResponse();
    }

    /**
     * Create an instance of {@link ServiceException }
     * 
     */
    public ServiceException createServiceException() {
        return new ServiceException();
    }

    /**
     * Create an instance of {@link PersonRequest }
     * 
     */
    public PersonRequest createPersonRequest() {
        return new PersonRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://example.com/", name = "personRequest")
    public JAXBElement<PersonRequest> createPersonRequest(PersonRequest value) {
        return new JAXBElement<PersonRequest>(_PersonRequest_QNAME, PersonRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://example.com/", name = "originRequest")
    public JAXBElement<PersonRequest> createOriginRequest(PersonRequest value) {
        return new JAXBElement<PersonRequest>(_OriginRequest_QNAME, PersonRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://example.com/", name = "personResponse")
    public JAXBElement<PersonResponse> createPersonResponse(PersonResponse value) {
        return new JAXBElement<PersonResponse>(_PersonResponse_QNAME, PersonResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://example.com/", name = "ServiceException")
    public JAXBElement<ServiceException> createServiceException(ServiceException value) {
        return new JAXBElement<ServiceException>(_ServiceException_QNAME, ServiceException.class, null, value);
    }

}
